### PR TITLE
Modify mrtx to parse entire MRT file for a single record error enhancement

### PR DESCRIPTION
**Pull request by sanketsharma411**
PR for issue #28

### CODE REVIEW

**Comment by hadiasghari** [comment]
Thanks a lot. I'll need a few days to merge this. Btw, Travis is failing on Python 3.x, have you checked that?

**Comment by sanketsharma411** [comment]
@hadiasghari: yeah, I am on it!

**Comment by sanketsharma411** [comment]
@hadiasghari : Done!

**Comment by hadiasghari** [comment]
@sanketsharma411 thank you, merged!

**Pull request merged**
