### PR TITLE
Implementing get_as_name method

### PR DESCRIPTION
**Pull request by italomaia**
get_as_name implemented with support for .json files

### CODE REVIEW

**Comment by hadiasghari** [comment]
@anoroozian have a look through it and then follow comments on issue #21 :)

**Comment by italomaia** [comment]
Parsel was replaced by a regular expression. Some performance was lost along the way, but not much. Now the html file can be persisted and reused.

**Comment by anoroozian** [comment]
@hadiasghari I pulled the patch and tried it out. Its great. 
I think we should pull and merge the code but I think a few tweaks will make it easier to use.
We can implement the tweaks our self.

For example the current implementation requires a string conversion which I think is not necessary:
```
db = pyasn.pyasn(_SOME_FILE_, as_names_file=_SOME_JSON_FILE_)
asn, prefix = db.lookup("8.8.8.8")
db.get_as_name(str(asn))
```

Instead we can store the JSON with integer keys and instead get this:
```
db = pyasn.pyasn(_SOME_FILE_, as_names_file=_SOME_JSON_FILE_)
asn, prefix = db.lookup("8.8.8.8")
db.get_as_name(asn)
```

Thanks @italomaia for the implementation.

**Comment by italomaia** [comment]
Both tweaks are quite doable. Let's me see ...

**Pull request merged**
