### PR TITLE
Update get_as_size for ipv4/ipv6 

### PR DESCRIPTION
**Pull request by trolldbois**
Fix description and code of get_as_size to only count prefix size for IPv4.
Add get_as_size _v6 to count prefix size for IPv6 prefixes

### CODE REVIEW

**Comment by trolldbois** [comment]
Include a bugfix: current count is wrong as it miscalculate the size of IPv6 prefixes, as documented in #19 .
This would fix #19

**Comment by hadiasghari** [comment]
Hi [trolldbois](https://github.com/trolldbois), Thank you for submitting this PR and noticing this bug. Wouldn't it be better if a whole new method is not created for v6, but rather, inside get_as_size(), it returns the sum of both numbers? Or perhaps you had some motivation behind creating a separate method, in which case I'd be curious to know about it.

**Comment by trolldbois** [comment]
@hadiasghari I chose to add a new method to maintain backward functionality where most users would expect get_as_size to return the number of IPV4 address, (up to 2**32, often thousands to hundred of thousands) per previous code logic.
The addition of IPv6 counts would make that number irrelevant as announced IPv6 prefixes start at /48, so the results are numbers in the billions of billions, completely useless really.
So I removed the IPv6 prefix count error from the original logic, and move it to a separate method, just in case somebody cares about how many trillions of IPv6 are being routed in an AS.

**Comment by hadiasghari** [comment]
That makes sense, thanks for the explanation!

**Pull request merged**
